riot:
  api:
    key: RGAPI-6dda3abc-25fa-44ae-b2c6-91841db029ff
jwt:
  secret:
    key: N+TdXgKtO/HfBx0vX6ZCaDe/F51z/APPL0PAuj3M6HmZIBd3eTiDGK1y8Qq5y5nPwUKWTkoyLaV2u16wvOhnSA==
spring:
  datasource:
    url: jdbc:mysql://database-2.c10e80scofbi.ap-northeast-2.rds.amazonaws.com:3306/riotdatadb?useSSL=false&serverTimezone=UTC
    username: admin
    password: tmvkfmxkzheld12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true

  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 운영에서는 validate 또는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 버전에 맞는 Dialect 사용
        format_sql: true
        show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug # SQL 디버그 정보 출력